### ISSUE TITLE
能不能通过vercel环境变量来更改反代网站

### ISSUE THREAD

**Issue by bian2022** [gaowanlu/google#17]
# 说一下改github文件来修改的弊端
1. 一个账号只允许有一个这个仓库的分支，如果我想要反代好几个（比方说谷歌githubv2ex）需要把项目下载到本地，再上传，这会导致如果项目进行了更新，我无法快速同步更新
2. 修改起来不如ve部署的时候容易

---
# 支持的好处
1. ve允许一个github项目多次部署，部署的时候填个要反代域名的环境变量就行了
2. 修改反代网站跟容易

---
# 因此希望开发者可以考虑下我的建议

**Comment by gaowanlu** [comment]
You can change api/proxy.js by yourself. In fact, this code repository is more like a template, and you can customize your own forwarding rules. Thank you for your feedback and support, and wish you the best in life.

**Comment by bian2022** [comment]
> You can change api/proxy.js by yourself. In fact, this code repository is more like a template, and you can customize your own forwarding rules. Thank you for your feedback and support, and wish you the best in life.

感谢你的回复
如果不支持就算了
祝您生活愉快！
