### ISSUE TITLE
vercel中绑定的域名无法访问

### ISSUE THREAD

**Issue by imnxg** [gaowanlu/google#8]
## 遇到的问题
![image](https://user-images.githubusercontent.com/73350203/236594597-e4107ef1-1a18-4173-b5d4-98ed6a18e018.png)
使用vercel提供的域名可以科学xx访问，但绑定自己的域名却访问不了，不论是数据流量还是科学xx都访问不了。

**Comment by gaowanlu** [comment]
有可能是本地网络问题，换个设备访问试试

**Comment by imnxg** [comment]
> 

手机端和电脑端都试过，还是不能访问，在cloudfare中关闭cdn加速也不行，也是只有vercel提供的域名可以访问！

**Comment by imnxg** [comment]
应该是不能使用cdn加速，关闭cdn有缓存
